- name: Setup Nginx using Jinja2 template
  hosts: all
  become: yes
  vars:
    backend_port: 8080

  tasks:
    - name: Enable nginx in amazon-linux-extras
      command: amazon-linux-extras enable nginx1
      args:
        creates: /etc/yum.repos.d/amzn-nginx.repo
      when: ansible_distribution == "Amazon"

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Ensure Nginx conf directory exists
      file:
        path: /etc/nginx/conf.d
        state: directory
        mode: '0755'

    - name: Copy Nginx config from template
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/nginx.conf

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

